# Generated by Django 5.2.16 on 2026-08-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_simplify_roles'),
        ('authentication', '0006_fmmsuser_assigned_vehicle_id'),
    ]

    operations = [
    ]
